### ISSUE TITLE
Analyzer fails if data is stored as a list of unicode values

### ISSUE THREAD

**Issue by fortable1999** [whoosh-community/whoosh#321]
**[Original report](https://bitbucket.org/mchaput/whoosh/issue/321) by Ashutosh Singla (Bitbucket: [ashu1461](https://bitbucket.org/ashu1461), GitHub: [ashu1461](https://github.com/ashu1461)).**

----------------------------------------

```
#!python

def item_name_analyzer():
    """
    Analyzer behaviour:

    Input: u"some item name", u"SomeItem/SubItem", u"GSOC2011"

    Output: u"some", u"item", u"name"; u"Some", u"Item", u"Sub", u"Item"; u"GSOC", u"2011"
    """
    iwf = MultiFilter(index=IntraWordFilter(mergewords=True, mergenums=True),
                      query=IntraWordFilter(mergewords=False, mergenums=False)
                     )
    analyzer = RegexTokenizer(r"\S+") | iwf | LowercaseFilter()
    return analyzer

""" add two documents to the index """
writer.add_document(title=u"MyDocument", content=u"This is my document!",
                    path=u"/a", tags=u"first short", icon=u"/icons/star.png")
writer.add_document(title=[u"MyDocument"], content=u"This is the second example.",
                    path=u"/b", tags=u"second short", icon=u"/icons/sheep.png")

```
Consider using the item_name_analyzer defined above, if we search for "title":**u"Document"**, the one with the title **u"MyDocument"** gives a hit where as one with the title **[u"MyDocument"]** fails.

**Comment by ThomasWaldmann** [comment]
Just wondering:
- the issue was closed 2018-09-02 by @fortable1999 
- the issue was marked major bug 2018-12-10 by @fortable1999 

How does it make sense?

Was the bug fixed? Link to fix?
