### ISSUE TITLE
Whoosh goes into infinite loop

### ISSUE THREAD

**Issue by fortable1999** [whoosh-community/whoosh#461]
**[Original report](https://bitbucket.org/mchaput/whoosh/issue/461) by SMour (Bitbucket: [SMour](https://bitbucket.org/SMour), GitHub: [SMour](https://github.com/SMour)).**

----------------------------------------

Under two conditions whoosh goes into infinite loop:
1. UnionMatcher - skip_to_quality        
Refer issue - https://bitbucket.org/mchaput/whoosh/issues/446/infinite-loop-in-unionmatcher       
2. AndMaybeMatcher - skip_to_quality      
Case when:          
1. aq + bq == minquality       
2. aq > bq       
3. bq = b.block_quality() evaluates to the same value each time leading to infinite loop
4. skipped += b.skip_to_quality(minquality - aq) always evalutes to zero due to internal floating point comparison of variables differing at 16th precision point

**Comment by stevennic** [comment]
I'm encountering the same issue. Paste of issue # 494 from the Bitbucket repo:
Stack:
skip_to_quality, binary.py:780
matches, collectors.py:409
collect_matches, collectors.py:737
run, collectors.py:144
search_with_collector, searching.py:819
search, searching.py:786

Variables
a = IntersectionMatcher(IntersectionMatcher(UnionMatcher(UnionMatcher(W3LeafMatcher(('phrase', b'1ml'), True), UnionMatcher(W3LeafMatcher(('includes', b'pipet'), False), W3LeafMatcher(('capacity', b'1ml'), True))), W3LeafMatcher(('phrase', b'serological'), True)), W3LeafMatcher(('type', b'serological'), True)), W3LeafMatcher(('type', b'pipet'), True))
aq = 61.176883761923335
b = W3LeafMatcher(('phrase', b'pipet'), True)
bq = 4.324152655016125
minquality = 65.50103641693946
self = AndMaybeMatcher(IntersectionMatcher(IntersectionMatcher(UnionMatcher(UnionMatcher(W3LeafMatcher(('phrase', b'1ml'), True), UnionMatcher(W3LeafMatcher(('includes', b'pipet'), False), W3LeafMatcher(('capacity', b'1ml'), True))), W3LeafMatcher(('phrase', b'serological'), True)), W3LeafMatcher(('type', b'serological'), True)), W3LeafMatcher(('type', b'pipet'), True)), W3LeafMatcher(('phrase', b'pipet'), True))
skipped = 0

The while loop never ends. It goes into the else clause, where skipped always remains zero and bq remains unchanged.

The whoosh entrypoint is this point in my code:
og = qparser.OrGroup
query = MultifieldParser(schema.names(), schema, group=og).parse(phrase)
searcher.search(query, mask=whoosh.query.Term("id", pid), limit=5)
^ infinite loop

**Comment by fortable1999** [comment]
Thanks for your PR!
I'd like merge & close this issue.
