### ISSUE TITLE
Parsing crashes when using ranges with grouping in a query

### ISSUE THREAD

**Issue by fortable1999** [whoosh-community/whoosh#480]
**[Original report](https://bitbucket.org/mchaput/whoosh/issue/480) by Justin Trudell (Bitbucket: [justindefence](https://bitbucket.org/justindefence), GitHub: Unknown).**

----------------------------------------

Hi,

Thanks for building Whoosh - it's overall a fantastic repo that really helped me accomplish what I was hoping to do.

However, when testing various flows recently, I've discovered what seems to be a bug that crashes the parsing when a certain input is passed in.

I've uploaded a file that exemplifies the bug. It looks like the bug is caused by the combination of using a group with ranges inside, because when the parentheses are removed, the string parses correctly.

Please let me know if any more clarification is needed or if this is actually improper use on my end, and thanks for your help!

**Comment by nijel** [comment]
Fixed by https://github.com/whoosh-community/whoosh/pull/536
