### ISSUE TITLE
Highlight Excerpts Are Not Consistent

### ISSUE THREAD

**Issue by fortable1999** [whoosh-community/whoosh#491]
**[Original report](https://bitbucket.org/mchaput/whoosh/issue/491) by Andreas (Bitbucket: [aeroclick](https://bitbucket.org/aeroclick), GitHub: Unknown).**

----------------------------------------

Every time I repeat a search, excerpts change, rotating between a few candidates. 

I have tried almost all of the highlight customization options you have on your website with no success.

So I would very much like to hear from you if this is just the normal Whoosh behavior and how it could be solved in terms of giving Whoosh a rule to follow and be consistent.

A quick workaround I found is to set the top parameter to something like 30+.

Thanks a lot !

**Comment by infosisio** [comment]
Yeah this is a major bug indeed.

**Comment by fortable1999** [comment]
The reason is this line:
https://github.com/whoosh-community/whoosh/blob/master/src/whoosh/highlight.py#L154

whoosh use fragment score as first order and compares python object id for second order.
In case fragments have same score, it will compare their object id
But i think it's not very meaningful use object id which may be difference every time.

So I'd like use first char index & last char index for secondary order.

**Comment by fortable1999** [comment]
I solved this problem in this pull request:
https://github.com/whoosh-community/whoosh/pull/517

**Comment by fortable1999** [comment]
I'd like close this issue.
