### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by nijel** [whoosh-community/whoosh#500]
The original repository had [release tags](https://bitbucket.org/mchaput/whoosh/downloads/?tab=tags), but there are [none on the github](https://github.com/whoosh-community/whoosh/releases). Maybe these were just omitted when doing the migration (perhaps `git push --tags` was forgotten?).

**Comment by fortable1999** [comment]
I made mistakes using the converting tool for hg to git.
I will try to fix & push tags information.

**Comment by fortable1999** [comment]
Hi, I pushed all the tags from bitbucket.
