### ISSUE TITLE
Cannot Search for C++

### ISSUE THREAD

**Issue by infosisio** [whoosh-community/whoosh#533]
Whoosh is not willing to accept terms like C++ for search, it gets confused with the plus operator being interpreted as some special query.

I think this is a problem, ElasticSearch doesn't suffer from it.

**Comment by infosisio** [comment]
@nijel If you happen to have an easy answer for this, I thought of asking you as you use it in a production environment and mine depends on supporting programming languages that have queries like "C++", thanks in advance!

**Comment by nijel** [comment]
Sorry, I have no experience with this, for my use case ignoring such chars is actually preferred behavior.

Anyway your report lacks any information to reproduce it, most importantly how do you perform the queries. Do you construct them yourself or do you use query parser?

If you're using query parser, it does quite some interpreting, try removing plugins you do not use when constructing it (eg. by passing `plugins=[]`).

**Comment by infosisio** [comment]
@nijel Thanks a lot for being as helpful as you could!

**Comment by infosisio** [comment]
**Update**: Even removing all plugins, it's still the same. 

I don't know what's up but I am pretty certain others will bump into this eventually, so it would be good if somebody who cares for the project looks into it.

**Comment by nijel** [comment]
I have looked into it and it works without any problems:

```python
from __future__ import with_statement, unicode_literals, print_function

from whoosh import fields
from whoosh.util.testing import TempIndex
from whoosh.query import Term
from whoosh import analysis

sc = fields.Schema(id=fields.ID(stored=True), text=fields.TEXT(analyzer=analysis.KeywordAnalyzer()))

with TempIndex(sc, "languages") as ix:
    with ix.writer() as writer:
        writer.add_document(id='1', text='c++ language')
        writer.add_document(id='2', text='c language')
        writer.add_document(id='3', text='python language')

    with ix.searcher() as searcher:
        print('Matches for c:', list(searcher.search(Term('text', 'c'))))
        print('Matches for c++:', list(searcher.search(Term('text', 'c++'))))
        print('Matches for python', list(searcher.search(Term('text', 'python'))))
```

Produces:

```
Matches for c: [<Hit {'id': u'2'}>]
Matches for c++: [<Hit {'id': u'1'}>]
Matches for python [<Hit {'id': u'3'}>]
```

My another guess is that you are using `StandardAnalyzer`, which by default captures only strings consisting of only word chars with minimal length of two. So that apparently won't properly index neither `c` nor `c++` string. But it would be *great* if you included more information in the report such as schema you're using and how you build the query, without that it's just guessing where is problem in *your* code.

**Comment by infosisio** [comment]
@nijel Yep your guess must be right. Next time will include more details. Thanks a lot anyhow!
