### ISSUE TITLE
Resolved: help changing operators

### ISSUE THREAD

**Issue by dorel14** [whoosh-community/whoosh#555]
hello 
I've tried this code from help to change operators
`        op = qparser.OperatorsPlugin(And="+",
                                     Or="\\|",
                                     AndNot="&!",
                                     AndMaybe="&~",
                                     Not="\\-")
        q.replace_plugin(op)`

when i try to search , it crashes with this message 
`File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/utils/pool.py", line 21, in run
    func(*args, **kargs)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/dispatch.py", line 50, in handle_event
    self._dispatch_listeners(listeners, event)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/dispatch.py", line 104, in _dispatch_listeners
    l['function'](message, **match.groupdict())
  File "/home/pi/projets/supportBot/mybot/plugins/faqsearch.py", line 60, in searchIndex
    Not=u"\\-")
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/whoosh/qparser/plugins.py", line 940, in __init__
    ops.append((ot(And, syntax.AndGroup, memo="and"), 0))
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/whoosh/qparser/plugins.py", line 909, in __init__
    RegexTagger.__init__(self, expr)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/whoosh/qparser/taggers.py", line 57, in __init__
    self.expr = rcompile(expr)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/whoosh/util/text.py", line 132, in rcompile
    return re.compile(pattern, re.UNICODE | flags)
  File "/home/pi/projets/supportBot/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/home/pi/projets/supportBot/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/pi/projets/supportBot/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/home/pi/projets/supportBot/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/home/pi/projets/supportBot/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/home/pi/projets/supportBot/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
`

Is it a bug or something wrong in my code ?

**Comment by stevennic** [comment]
That's because you're improperly escaping your new operators. They must be valid regular expressions, but since `+` is a special RE character, you must escape it. I think also your double backslash for `Or` and `Not` is redundant; you just need one, otherwise you're telling Whoosh that your `Or` operator is `\|`.

So the correct syntax is:
`op = OperatorsPlugin(And="\+", Or="\|", AndNot="&!", AndMaybe="&~", Not="\-")`

**Comment by dorel14** [comment]
Ok i'll try it , this code is taken directly from documentation , it ight be nice to change it

**Comment by stevennic** [comment]
Oh if so the doc needs to be changed, thanks for letting me know.

**Comment by dorel14** [comment]
Hi , 
I've tried this
op = OperatorsPlugin(And="\\+",
                                 Or="\\|",
                                 AndNot="&!",
                                 AndMaybe="&~",
                                 Not="\\-")

And as result i have this 
`AttributeError: 'Or' object has no attribute 'replace_plugin'`

Is it normal ?

**Comment by stevennic** [comment]
Can you post a complete code section? There's not enough context here to tell.

**Comment by dorel14** [comment]
The complete code
`def rechdocs():
        recherche = bottle.request.forms.get('rechdoc')
        ix = open_dir(cache_path, indexname='doc_technique')
        with ix.searcher(weighting=scoring.TF_IDF()) as searcher:
            query = MultifieldParser(["name",
                                      "lower_name",
                                      "subfolders",
                                      "content"], ix.schema).parse(recherche)
            op = OperatorsPlugin(And="\\+",
                                 Or="\\|",
                                 AndNot="&!",
                                 AndMaybe="&~",
                                 Not="\\-")
            query.replace_plugin(op)
            query.add_plugin(FuzzyTermPlugin())
            results = searcher.search(query, limit=None)
            nbresults = len(results)
            resultats = []
            for r in results:
                resultats.append(r)
                print(r.score, r['name'], r['type'])
                print(resultats)
        return bottle.template('wikiintegration.tpl',
                               title2='Wiki',
                               nbresults=nbresults,
                               resultats=resultats)
`

**Comment by dorel14** [comment]
Resolved myself

The final code
`def rechdocs():
        recherche = str(bottle.request.forms.get('rechdoc'))
        ix = open_dir(cache_path, indexname='doc_technique')
        with ix.searcher(weighting=scoring.TF_IDF()) as searcher:
            parser = MultifieldParser(["name",
                                       "lower_name",
                                       "subfolders",
                                       "content"], ix.schema)
            op = OperatorsPlugin(And="\\+",
                                 Or="\\|",
                                 AndNot="&!",
                                 AndMaybe="&~",
                                 Not="\\-")
            parser.replace_plugin(op)
            parser.add_plugin(FuzzyTermPlugin())
            query = parser.parse(recherche)
            results = searcher.search(query, limit=None)
            nbresults = len(results)
            resultats = []
            for r in results:
                resultats.append(r)
                print(r.score, r['name'], r['type'])
                print(resultats)
        return bottle.template('wikiintegration.tpl',
                               title2='Wiki',
                               nbresults=nbresults,
                               resultats=resultats)`
